#!/usr/bin/env bash
# Generates tint2rc from this script. Called automatically by launch.sh.
# Edit this file — never edit tint2rc directly.
set -euo pipefail

OUT="$(dirname "$(realpath "$0")")/tint2rc"
FONT="JetBrainsMono Nerd Font Mono 10"
S="~/.config/tint2/scripts"

# Colored background: comment label, border_color, background_color
# All colored backgrounds share rounded=0, border_width=2, border_sides=TL
color_bg() {
    cat <<EOF
# $1
rounded = 0
border_width = 2
border_sides = TL
border_color = $2
background_color = $3

EOF
}

# Workspace execp block: workspace_name monitor_number
ws_block() {
    cat <<EOF
execp = new
execp_command = $S/workspace.sh $1
execp_interval = 0
execp_continuous = 1
execp_has_icon = 0
execp_markup = 1
execp_font = $FONT
execp_padding = 0 2
execp_background_id = 1
execp_centered = 1
execp_monitor = $2
execp_lclick_command = i3-msg workspace $1

EOF
}

# Status module execp block: command interval bg_id [font_color] [extra_key=val ...]
status_block() {
    local cmd=$1 interval=$2 bg=$3 color=${4:-#ffffff 100}
    shift $(( $# < 4 ? $# : 4 ))
    cat <<EOF
execp = new
execp_command = $cmd
execp_interval = $interval
execp_has_icon = 0
execp_continuous = 0
execp_markup = 0
execp_font = $FONT
execp_font_color = $color
execp_padding = 4 2
execp_background_id = $bg
execp_centered = 1
EOF
    for line in "$@"; do echo "$line"; done
    echo
}

{

cat <<'STATIC'
# Generated by generate.sh — edit that file, not this one.
# tint2rc — single full-width bar per monitor.
# Workspaces left, status modules right.
# execp_monitor 2 = HDMI-A-0 (right), execp_monitor 1 = DisplayPort-2 (left).

#-------------------------------------
# Backgrounds
#-------------------------------------

# 1: transparent
rounded = 1
border_width = 1
border_color = #000000 0
background_color = #000000 0

# 2: panel
rounded = 0
border_width = 3
border_sides = TLRB
border_color = #000000 58
background_color = #0f0d0d 98

STATIC

color_bg "3: snapshot"      "#bd3232 100" "#8b0000 100"
color_bg "4: spotify"       "#4e5a65 100" "#1c2833 100"
color_bg "5: disk"          "#aa7444 100" "#784212 100"
color_bg "6: cpu"           "#4c55b0 100" "#1a237e 100"
color_bg "7: memory"        "#7c558c 100" "#4a235a 100"
color_bg "8: volume"        "#3232dc 100" "#0000aa 100"
color_bg "9: weather"       "#4d9052 100" "#1b5e20 100"
color_bg "10: date"         "#ad6a32 100" "#7b3800 100"
color_bg "11: time/clock"   "#329296 100" "#006064 100"
color_bg "12: systray"      "#555555 100" "#222222 100"
color_bg "13: disk-storage" "#546e7a 100" "#37474f 100"

cat <<'STATIC'
#-------------------------------------
# Panel
#-------------------------------------
panel_items = E1E2E3E4E5E6E7E8E9E10FE11E12E13E14E15E16E17SC
panel_size = 100% 26
panel_margin = 0 0
panel_padding = 0 2 2
panel_dock = 0
panel_layer = bottom
panel_position = bottom left horizontal
panel_monitor = all
wm_menu = 0
panel_background_id = 2
panel_shrink = 0

#-------------------------------------
# System Tray
#-------------------------------------
systray_padding = 6 0 4
systray_background_id = 12
systray_sort = ascending
systray_icon_size = 16
systray_icon_asb = 100 0 0
systray_monitor = secondary

#-------------------------------------
# Clock
#-------------------------------------
time1_format = %I:%M %p
time1_font = JetBrainsMono Nerd Font Mono 10
time2_format =
clock_font_color = #ffffff 100
clock_padding = 6 2
clock_background_id = 11
clock_lclick_command =
clock_rclick_command =

#-------------------------------------
# E1-E5: R workspaces (monitor 2 = HDMI-A-0)
#-------------------------------------
STATIC
for ws in R1 R2 R3 R4 R5; do ws_block "$ws" 2; done

cat <<'STATIC'
#-------------------------------------
# E6-E10: L workspaces (monitor 1 = DisplayPort-2)
#-------------------------------------
STATIC
for ws in L1 L2 L3 L4 L5; do ws_block "$ws" 1; done

cat <<'STATIC'
#-------------------------------------
# E11-E19: status modules
#-------------------------------------
STATIC

status_block "$S/snapshot.sh"                  60    3
status_block "$S/spotify.sh"                    5    4  "#81b71a 100" \
    "execp_lclick_command = playerctl --player=spotify play-pause"
status_block "$S/disk-root.sh"                 30    5
status_block "$S/disk-storage.sh"              30   13
status_block "$S/volume.sh"                     5    8  "#ffffff 100" \
    "execp_lclick_command = pactl set-sink-mute @DEFAULT_SINK@ toggle" \
    "execp_rclick_command = pavucontrol &" \
    "execp_uwheel_command = pactl set-sink-volume @DEFAULT_SINK@ +5%" \
    "execp_dwheel_command = pactl set-sink-volume @DEFAULT_SINK@ -5%"
status_block "~/.config/i3blocks/scripts/wttr" 1800   9  "#ffffff 100" \
    "execp_lclick_command = gnome-weather"
status_block "$S/date.sh"                      60   10  "#ffffff 100" \
    "execp_lclick_command = orage"

} > "$OUT"
