#!/bin/sh
set -eu

if [ -n "${BLOCK_BUTTON:-}" ]; then
    gnome-calendar >/dev/null 2>&1 &
fi

case "${1:-datetime}" in
    date)
        date '+%m-%d-%Y'
        ;;
    clock)
        date '+%I:%M %p'
        ;;
    *)
        date '+%m-%d-%Y %I:%M %p'
        ;;
esac
