#!/bin/sh
set -eu

if [ -n "${BLOCK_BUTTON:-}" ]; then
    case "${1:-datetime}" in
        # clock) gnome-clocks >/dev/null 2>&1 & ;;
        *)     orage >/dev/null 2>&1 & ;;
    esac
fi

case "${1:-datetime}" in
    date)
        date '+%m-%d-%Y'
        ;;
    clock)
        date '+%I:%M %p'
        ;;
    *)
        date '+%m-%d-%Y %I:%M %p'
        ;;
esac
