#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 1 2 3 4 5

#focus options:
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false
bspc config focus_by_distance true
bspc config history_aware_focus false

bspc config border_width 2
bspc config window_gap 5
bspc config top_padding 30

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

xsetroot -cursor_name left_ptr &

feh --bg-scale ~/walls/bladerunner.png
xinput --set-prop 'SteelSeries SteelSeries Rival 710 Gaming Mouse' 300 -0.5

bspc monitor HDMI-0 -s DP-0

#$HOME/.config/polybar/launch.sh
xfce4-panel --disable-wm-check &
