#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 1 2 3 4 5 

#focus options:
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor false
bspc config pointer_follows_focus false
bspc config focus_by_distance true
bspc config history_aware_focus false

bspc config border_width         2
bspc config window_gap           5 
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#applications:
bspc rule -a 'Alacritty:calcurse' state=floating

xrandr --output DP-0 --primary --mode 1920x1080 --rate 240 --rotate normal 
xrandr --output HDMI-0 --mode 1920x1080 --rate 75 --rotate normal --left-of DP-0

xsetroot -cursor_name left_ptr &

feh --bg-scale ~/wallpapers/hermes.jpg

bspc monitor HDMI-0 -s DP-0


$HOME/.config/polybar/launch.sh

