#!/bin/bash
set -euo pipefail

rofi_theme='
window {
  width: 760px;
  location: center;
  anchor: center;
}

entry {
  placeholder: "filter open windows";
}

listview {
  lines: 8;
  columns: 1;
  fixed-height: true;
  cycle: true;
  dynamic: true;
  scrollbar: true;
  spacing: 0;
  padding: 2px;
}

element {
  spacing: 8px;
}

element-icon {
  size: 18px;
}

element-text {
  vertical-align: 0.5;
}
'

rofi -show window \
  -markup \
  -show-icons \
  -window-format '<b>{t}</b>	<small><i>({w}  {c})</i></small>' \
  -p 'Windows' \
  -theme-str "$rofi_theme"
