#!/bin/bash
num="$1"

focused_workspace=$(
  i3-msg -t get_workspaces |
  jq -r '.[] | select(.focused) | .name'
)

focused_output=$(
  i3-msg -t get_workspaces |
  jq -r '.[] | select(.focused) | .output'
)

case "$focused_workspace" in
    L*) prefix="L" ;;
    R*) prefix="R" ;;
esac

case "${prefix:-}:$focused_output" in
    :HDMI-1|:HDMI-A-0)       prefix="L" ;;
    :DP-3|:DisplayPort-2)    prefix="R" ;;
    :*)                      prefix="L" ;;
esac

i3-msg "workspace ${prefix}${num}"
